#!/usr/bin/env bash
# does dns resolution

if ! [ -z $1 ]; then
	if [ -z $2 ]; then
		dig "www.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | \
			awk '{ print "The subdomain www is a "$4" record and points to "$5 }'
		dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | \
			awk '{ print "The subdomain www is a "$4" record and points to "$5 }'
		dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | \
			awk '{ print "The subdomain www is a "$4" record and points to "$5 }'
		dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | \
			awk '{ print "The subdomain www is a "$4" record and points to "$5 }'
	else
		dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | \
			awk '{ print "The subdomain www is a "$4" record and points to "$5 }'
	fi
fi
