#!/usr/bin/env bash
# does dns resolution

dig_name() {
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n 1 | \
		awk -v dom="$2" '{print "The subdomain " dom " is a "$4" record and points to "$5 }'
}
if [ -n "$1" ]; then
	if [ -z "$2" ]; then
		for sub in www lb-01 web-01 web-02
		do
			dig_name "$1" "$sub"
		done
	else
		dig_name "$1" "$2"
	fi
fi
