#!/usr/bin/env bash
# install nginx
conf="server { 
listen 80 default_server; 
listen [::]:80 default_server; 
root /var/www/html;
# Add index.php to the list if you are using PHP 
index index.html index.htm index.nginx-debian.html;
error_page 404 403 500 503 /error-page.html;
server_name _;
location / {
# First attempt to serve request as file, then 
# as directory, then fall back to displaying a 404.
try_files \$uri \$uri/ =404;
}
location /redirect_me {
rewrite ^/redirect_me(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
}
location = /error-page.html {
internal;
}
}"
apt-get install nginx -y
rm /var/www/html/index*.html
echo 'Hello World!' > /var/www/html/index.html
echo "$conf" > /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error-page.html
service nginx restart
